services:
  _defaults:
    autowire: false

  Kczer\ExcelImporterBundle\Importer\Factory\ModelExcelImporterFactory:
    autowire: true
    public: true

  Kczer\ExcelImporterBundle\Importer\ModelExcelImporter:
    shared: false
    autowire: true
    public: true

  Kczer\ExcelImporterBundle\Exporter\ModelExcelExporter:
    shared: false
    autowire: true
    public: true

  Kczer\ExcelImporterBundle\ExcelElement\Factory\ExcelCellFactory:
    autowire: true

  Kczer\ExcelImporterBundle\ExcelElement\Factory\ExcelRowFactory:
    autowire: true

  Kczer\ExcelImporterBundle\ExcelElement\Factory\ReverseExcelCellFactory:
    autowire: true

  Kczer\ExcelImporterBundle\ExcelElement\Factory\ReverseExcelCellManagerFactory:
    autowire: true

  Kczer\ExcelImporterBundle\Model\Factory\ModelFactory:
    autowire: true

  Kczer\ExcelImporterBundle\Model\Factory\ModelMetadataFactory:
    autowire: true

  Kczer\ExcelImporterBundle\Test\TestDictionaryClass:
    autowire: true
    public: true
    shared: false

  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\:
    resource: '../../ExcelElement/ExcelCell/*'
    exclude: '../../ExcelElement/ExcelCell/{Configuration,Validator,BoolExcelCell.php}'
    arguments:
      $translator: '@translator'
    shared: false
    public: true

  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\BoolExcelCell:
    public: true
    arguments:
      $translator: '@translator'
      $trueValues: '%excel_cell.bool.true_values%'
      $falseValues: '%excel_cell.bool.false_values%'
      $emptyAsFalse: '%excel_cell.bool.empty_as_false%'

  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\AbstractDictionaryExcelCell:
    arguments:
      $translator: '@translator'
    shared: false
    abstract: true
    public: true

  Kczer\ExcelImporterBundle\ExcelElement\ReverseExcelCell\:
    resource: '../../ExcelElement/ReverseExcelCell/*'
    exclude: '../../ExcelElement/ReverseExcelCell/{BoolReverseExcelCell.php}'
    shared: false
    public: true

  Kczer\ExcelImporterBundle\ExcelElement\ReverseExcelCell\BoolReverseExcelCell:
    shared: false
    public: true
    arguments:
      $translator: '@translator'
      $emptyAsFalse: '%excel_cell.bool.empty_as_false%'

  Kczer\ExcelImporterBundle\Util\TemporaryFileManager:
    shared: false