services:
  _defaults:
    autowire: true
  Kczer\ExcelImporterBundle\Importer\Factory\ModelExcelImporterFactory:
    public: true
  Kczer\ExcelImporterBundle\Importer\ModelExcelImporter:
    public: true
  Kczer\ExcelImporterBundle\ExcelElement\Factory\ExcelCellFactory:
  Kczer\ExcelImporterBundle\ExcelElement\Factory\ExcelRowFactory:
  Kczer\ExcelImporterBundle\Model\Factory\ModelFactory:
  Kczer\ExcelImporterBundle\Model\Factory\ModelMetadataFactory:
  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\AbstractDictionaryExcelCell:
    shared: false
    abstract: true
    public: true
  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\BoolExcelCell:
    shared: false
    public: true
  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\FloatExcelCell:
    shared: false
    public: true
  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\IntegerExcelCell:
    shared: false
    public: true
  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\StringExcelCell:
    shared: false
    public: true
  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\DateTimeExcelCell:
    shared: false
    public: true