services:
  _defaults:
    autowire: false

  Kczer\ExcelImporterBundle\Importer\Factory\ModelExcelImporterFactory:
    autowire: true
    public: true

  Kczer\ExcelImporterBundle\Importer\ModelExcelImporter:
    autowire: true
    public: true

  Kczer\ExcelImporterBundle\ExcelElement\Factory\ExcelCellFactory:
    autowire: true

  Kczer\ExcelImporterBundle\ExcelElement\Factory\ExcelRowFactory:
    autowire: true

  Kczer\ExcelImporterBundle\Model\Factory\ModelFactory:
    autowire: true

  Kczer\ExcelImporterBundle\Model\Factory\ModelMetadataFactory:
    autowire: true

  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\:
    resource: '../src/ExcelElement/ExcelCell/*'
    arguments:
      - '@translator'
    shared: false
    public: true

  Kczer\ExcelImporterBundle\ExcelElement\ExcelCell\AbstractDictionaryExcelCell:
    arguments:
      - '@translator'
    shared: false
    abstract: true
    public: true